#좌석 선택 영역
#A(ax,ay)와 B(bx,by) 좌표 구한 후 (ax, ay, bx-ax, by-ay)
SEARCH_REGION_ax = 20
SEARCH_REGION_ay = 143
SEARCH_REGION_bx = 678
SEARCH_REGION_by = 759

SEARCH_REGION = (SEARCH_REGION_ax, SEARCH_REGION_ay, SEARCH_REGION_bx-SEARCH_REGION_ax, SEARCH_REGION_by-SEARCH_REGION_ay)
#좌석 새로고침하는 버튼 영역
REFRESH_REGION_ax = 795
REFRESH_REGION_ay = 670
REFRESH_REGION_bx = 899
REFRESH_REGION_by = 688
REFRESH_REGION = (REFRESH_REGION_ax, REFRESH_REGION_ay, REFRESH_REGION_bx-REFRESH_REGION_ax, REFRESH_REGION_by-REFRESH_REGION_ay)
# 다음단계 버튼 좌표
CLICK_DESTINATION = (832, 641)

# 티켓 버튼 좌표
CLICK_TICKET = (719, 586)

# 티켓 타겟 색깔 
# TARGET_COLOR = (159,212,39) #테이블석(2인)
# TARGET_COLOR = (68,125,168) #1루 일반석
# TARGET_COLOR = (251,126,78) # 오렌지색 #TEST용도
# TARGET_COLOR = (123,104,238) # 포도알색깔 #TEST용도
TARGET_COLOR = (68,125,168)

# 예매 url
RESERVATION_URL = "https://tickets.interpark.com/special/sports/promotion?seq=27"